### ISSUE TITLE
For-hire Slic3r work

### ISSUE THREAD

**Issue by arthurwolf** [sapir/sonare#30]
Hello !

Really sorry for contacting you through an issue, I did not find your email anywhere, so this is the only way I found of getting your attention. Please feel free to ignore this if this is any kind of a bother, I apologize immensely if it is.

I am looking for somebody to hire to do custom work in Slic3r. We are talking about adding features, some for my company, others for two other companies also interested in Slic3r improvements. The features ( most of them ) would be generally useful to users in the community, and therefore we would essentially be paying somebody ( could be you ) to improve Slic3r.

Are you interested/do you have time to do for-hire work coding new features into Slic3r? If so please contact me. If you don't have the time or don't have the interest, could you recommend somebody you think might have time and/or interest in doing so?
This is paid work, the code would, of course, be Open-Source, and most of the code would be generally useful to the Open-Source 3D printing community, this is a win-win-win scenario ( at least from my perspective ).

My contact is : wolf.arthur@gmail.com

Thanks again !! If you consider this spam I apologize again !

**Comment by sapir** [comment]
Sorry, I'm not interested.

**Comment by arthurwolf** [comment]
Really sorry for bothering you, I got some positive answers from other Slic3rers so I'm all good anyway, have a nice day !
